# dreampay.github.io
theme: jekyll-theme-minimal
baseurl: "/dreampay.github.io"

title: DreamPay Documentation
description: One wallet. Endless possibilities.

markdown: kramdown
kramdown:
  input: GFM
